global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'data-pipeline'
    static_configs:
      - targets: ['data-pipeline:8000']

  - job_name: 'model-training'
    static_configs:
      - targets: ['model-training:8000']

  - job_name: 'inference-service'
    static_configs:
      - targets: ['inference-service:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']